tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/services"
tap "oven-sh/bun"
brew "bash"
brew "bat"
brew "python@3.12"
brew "diffutils"
brew "direnv"
brew "fd"
brew "fnm"
brew "fzf"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "graphviz"
brew "htop"
brew "jq"
brew "just"
brew "krb5"
brew "mas"
brew "neovim"
brew "pkg-config"
brew "poetry"
brew "prettier"
brew "python@3.10"
brew "ripgrep"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "speedtest-cli"
brew "stylua"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"
brew "typst"
brew "vim"
brew "watch"
brew "wget"
brew "oven-sh/bun/bun"
cask "docker"
cask "google-cloud-sdk"
cask "iina"
cask "libreoffice"
cask "notion"
cask "obs"
cask "obsidian"
cask "postman"
cask "raycast"
cask "slack"
cask "stats"
cask "stremio"
cask "visual-studio-code"
cask "whatsapp"
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Auto HD FPS for YouTube", id: 1546729687
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark Desktop", id: 6445813049
mas "Telegram", id: 747648890
vscode "charliermarsh.ruff"
vscode "davidlday.languagetool-linter"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "nvarner.typst-lsp"
vscode "pkief.material-icon-theme"
vscode "tomoki1207.pdf"
vscode "vscodevim.vim"
