alias sp:=start-dpt-project

default:
    @just --list --unsorted

# start dpt project
start-dpt-project DIR:
    @./scripts/start-dpt-project.sh {{DIR}}

# start sgsi
sgsi: (start-dpt-project 'magnet-sgsi')

# start dpt
dpt: (start-dpt-project 'magnet-dpt')

# start asset
asset: (start-dpt-project 'asset-intranet')

# start prisma
prisma: (start-dpt-project 'aes-essprim')

# start root
root: (start-dpt-project 'magnet-root-d3pt')

# start ats
ats: (start-dpt-project 'magnet-ats')

# start lifeplan cms
lp-cms: (start-dpt-project 'lifeplan-cms')

# start lifeplan sim
lp-sim: (start-dpt-project 'lifeplan-simulators')

# start mpc ticketing
mpc-ticketing: (start-dpt-project 'mpc-ticketing')

# start makitec erp
makitect-erp: (start-dpt-project 'makitec-erp')

# start aides backend
aides-backend:
    @./scripts/start-aides-backend.sh

# start aides frontend
aides-frontend:
    @./scripts/start-aides-frontend.sh

