alias sp:=start-dpt-project
alias cpdb:=copy-dpt-db

default:
    @just --list --unsorted

# start dpt project
start-dpt-project DIR:
    @./scripts/start-dpt-project.sh {{DIR}}

# start sgsi
sgsi: (start-dpt-project 'magnet-sgsi')

# start dpt
dpt: (start-dpt-project 'magnet-dpt')

# start asset
asset: (start-dpt-project 'asset-intranet')

# start prisma
prisma: (start-dpt-project 'aes-essprim')

# start root
root: (start-dpt-project 'magnet-root-d3pt')
